import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import Image from "next/image";
import { FiInfo } from "react-icons/fi";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>ACM UTSA</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className="flex min-h-screen flex-col items-center justify-center bg-[url('/img/bg.jpg')] bg-cover bg-no-repeat md:px-2">
				<div className="max-w-[1100px] bg-gray-500 p-10">
					<h1 className="font-sans text-5xl font-black text-white">
						The Association for Cute Megabears
					</h1>
					<h2 className="font-sans text-xl font-light text-gray-200">
						at UTSA
					</h2>
				</div>
			</main>
			<section className="min-h-screen bg-gray-200">
				<div className="flex h-[150px] items-center justify-center">
					<h1 className="font-sans text-3xl font-light text-gray-800">
						😳 About ACM 😳
					</h1>
				</div>
				<div className="mx-auto grid h-full max-w-[1100px] grid-cols-2">
					<div className="relative h-full">
						<Image
							src={"/img/dropin.jpg"}
							alt="A panda"
							width={500}
							height={1000}
						/>
					</div>
					<div>
						<p className="text-lg text-gray-700">
							The Association for Cute Megabears at UTSA is dedicated to giving
							members and pandas the opportunity to gain experience, network,
							socialize, learn, and grow outside of the bamboo in all fields of
							pandas and panda things.
						</p>
						<br />
						<div className="grid grid-cols-7">
							<div className="w-min">
								<FiInfo className="animate-spin text-5xl text-gray-700" />
							</div>
							<div className="col-span-6">
								<h1 className="text-2xl font-medium text-gray-700">
									Organization 🐼
								</h1>
								<p className="text-gray-500">
									Our chapter is organized to serve students for <s>academic</s>{" "}
									panda, <s>professional</s> panda, and <s>social</s> panda
									purposes at UTSA. The Chapter shall be involved with and
									conduct panda related activities that are included below.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section className="h-[600px] w-screen bg-[url('/img/funny.gif')] bg-cover bg-fixed"></section>
			<section className="h-min w-screen bg-gray-200 pb-10">
				<div className="flex h-[150px] items-center justify-center">
					<h1 className="font-sans text-4xl font-light text-gray-800">
						❤️❤️❤️ Our Sub Organizations ❤️❤️❤️
					</h1>
				</div>
				<div className="relative h-[500px] w-screen">
					<Image src={"/img/bnb3.png"} alt="Best Suborg" fill />
				</div>
			</section>
			<section className="h-[25000px] pb-10">
				<div className="flex h-[150px] items-center justify-center">
					<h1 className="font-sans text-4xl font-light text-gray-800">
						Contact Us
					</h1>
				</div>
				<div className="flex h-[calc(100%-150px)] items-end justify-center">
					<h2 className="font-bold tracking-[2rem] text-black">
						t e a m @ a c m u t s a . o r g
					</h2>
				</div>
			</section>
			<div className="flex min-h-[700px] w-screen flex-col items-center bg-black pb-10 text-white">
				<h1>
					I am too lazy to duplicate the footer, so instead here is another cute
					panda pic
				</h1>
				<Image src={"/img/cute.jpg"} alt="a panda" width={1000} height={1000} />
				<h1>Happy April Fools (and nuke ACMs SEO) Day!</h1>
			</div>
		</>
	);
};

export default Home;
